---
# tasks file for wordpress
- name: Download WordPress
  get_url: 
    url: https://ru.wordpress.org/wordpress-5.0.2-ru_RU.tar.gz
    dest: /tmp/wordpress.tar.gz
    validate_certs: no
  tags:
    - wp
    - wp-download

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html
    copy: no
  become: yes
  tags:
    - wp
    - wp-unarchive


- name: Chown wp dir
  file:
    path: /var/www/html/wordpress
    owner: nginx
    group: nginx
    recurse: yes
  become: yes
  tags:
    - wp
    - wp-chown

- name: Copy sample config file
  copy:
    src: wp-config.php
    dest: /var/www/html/wordpress/wp-config.php
    owner: nginx
    group: nginx
    mode: 0644
  tags:
    - wp
    - wp-copy-sample


#- name: Copy sample config file
#  command: /bin/mv /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php
#  args:
#    creates: /var/www/html/wordpress/wp-config.php
#  become: yes
#  tags:
#    - wp
#    - wp-copy-sample

- name: Restore selinux context for files
  command: /sbin/restorecon -R /var/www/html
  become: yes
  tags:
    - wp
    - wp-restorecon

#- name: Update WordPress config file
#  lineinfile:
#    dest=/var/www/html/wordpress/wp-config.php
#    regexp="{{ item.regexp }}"
#    line="{{ item.line }}"
#  with_items:
#    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{wp_mysql_db}}');"}        
#    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{wp_mysql_user}}');"}        
#    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{wp_mysql_password}}');"}
#    - {'regexp': "define\\('DB_HOST', '(.)+'\\);", 'line': "define('DB_HOST', '{{wp_mysql_server}}');"}
#  become: yes
#  tags:
#    - wp
#    - wp-update-conf
